grid_size: [128, 128] # if you load a movie, this will be overridden by the movie dimensions
max_steps: 500
action_type: run_tumble
observation_type: concentration
reward_type: step_penalty
render: true
seed: 123
plume: static

policy:
  spec: plug_and_play_demo:DeltaBasedRunTumblePolicy

observation_wrappers:
  - spec: plume_nav_sim.observations.history_wrappers:ConcentrationNBackWrapper
    kwargs:
      n: 2
